log = "2025-01-20 10:45:30 | INFO | Module=Telemetry | Status=PASS | Duration=123ms"

# Tasks:
#
# Extract the Module name
#
# Extract the Status
#
# Convert Duration to an integer (in ms)

new_log = log.split("|")
# module = None
d = {}
for i in new_log :
    if i.strip().startswith("Module="):
        module = i.split("=")[1]

    if "Duration" in i.strip() :
        Duration = int(i.split("=")[1].replace("ms", ""))
    # print(i)

print(module, Duration)

















#
# new_log = log.split("|")
# # print(new_log)
# for i in new_log:
#     items = i.strip()
#     # print(i)
#     if "Module" in items :
#         print(items[items.index("=")+1 :])
#     if "Status" in items :
#         print("Status = {}".format(items[items.index("=")+1:  ]))
#     if "Duration" in items :
#         l1 = items.split("=")
#         s1 = ""
#         for num in l1[1]:
#             if num.isnumeric() :
#                 s1 += num
#         print(int(s1))
#
# module = status = Duration = None
# for items in log.split("|"):
#     if items.startswith("Module="):
#         module = items.split("=")[1]
#     if items.startswith("Status"):
#         status = items.split("=")[1]
#     if items.startswith("Duration"):
#         Duration = int(items.split("=")[1].replace("ms", ""))
# result = (module, status, Duration)
#
# print(result)
# data = "10,20,30,40,50"

# Convert it into a list of integers
#
# Calculate:
#
# Sum
#
# Average
#
# Return the result as a dictionary
#
# 📌 Expected output:
#
# {
#     "values": [10, 20, 30, 40, 50],
#     "sum": 150,
#     "average": 30.0
# }

# data1 = data.split(",")
# # print(data1)
# d1 = {}
# data1 = []
# s1 = ""
# for i in data :
#     if i != ",":
#         s1 = s1 + i
#     else :
#         data1.append(int(s1))
#         s1 = ""
# data1.append(int(s1))
# print(data1)
#
# summ = 0
# for i in data1 :
#     summ = summ + i
# print(summ/len(data1))
#
# d1["data1"]= data1
# d1["summ"] = summ
# d1["average"] =summ/len(data1)
#
# print(d1)




# a = [1, 2, 3]
# b = a
# b.append(4)
#
# c = "test"
# d = c
# d = d + "_automation"
#
# print(a)
# print(c)



# Convert this into a dictionary
# Convert:
# cpu → integer 45
# memory → integer 1024
# disk → integer 80
# Keep status as string


# config = "cpu=45%;memory=1024MB;disk=80%;status=OK"
# cpu = memory = disk = None
# re_config = config.split(";")
# for i in re_config :
#     if i.startswith("cpu="):
#         cpu = i.split("=")[1].replace("%", "")
#     if i.startswith("memory="):
#         memory = int(i.split("=")[1].replace("MB", ""))

# print(memory)
# print(cpu)

# You are validating test IDs generated by an automation framework.
# A valid test ID must:
# Start with "TC_"
# End with a number
# Length must be ≥ 8 characters


# tc = ["TC_001", "TC_LOGIN_12", "tc_123", "TC_TEST"]
# for i in tc :
#     if i.startswith("TC_") and i[-1].isdigit() and len(i) >= 8 :
#         print(i)


# data = ["1", "2", "3"]
# result = data * 2
#
# data.append("4")
# print(result)
# print(data)

# Remove leading/trailing spaces
# Reduce multiple internal spaces to single spaces
# Convert the final string to uppercase

# s = "   ERROR:   Telemetry   failure   detected   "
# s1  = s.strip().replace("   ", " ")
# s2 = s1.strip()
#
# print(s1)



# s1 = "automation"
# s2 = "tionautoma"
# # print(s1.replace("a", "", 1 )+ "a")
# if s1.replace("a", "", 1 )+ "a" == s2 :
#     print("correct ")



# Count Occurrences (Case-Insensitive)
log = "Error error ERROR warning Warning INFO"

# print(count)

# new_log = log.lower().split()
# for i in new_log:
#     if i == "error":
#         print(new_log.count(i))
#         break



# Reverse Words, Not Characters
s = "Telemetry data validation failed"
s1 = []
# for i in s.split():
#     s1.append(i[::-1])
#
# print(s1)

# print(" ".join(s.split()[::-1]))


# cfg1 = "mode=debug;retry=3;timeout=30"
# cfg2 = "mode=release;retry=3;timeout=60"
#
# l1 = cfg1.split(";")
# l2 = cfg2.split(";")
# result1 = {}
# result2 = {}
# # print(l1)
# for item in l1 :
#     key,value = item.split("=" )
#     result1[key] = value
# for item in l2 :
#     key,value = item.split("=")
#     result2[key] = value
#
# print(result1)
# print(result2)
# diff ={}
#
# for k,v in result1.items():
#     if result1[k] != result2[k]:
#         diff[k] = (result1[k], result2[k])
# print(diff)





s1 = "aabbcddzz222"
s2 = "pqrsstupp"
#
# l1 = []
# for i in range(len(s1)):
#         l1.append(s1[i])
#         l1.append(s2[i])
# # print(l1)
# if len(s1) > len(s2):
#     l1.append(s1[len(s2):])
# if len(s1) == len(s2):
#     print("".join(l1))
# else :
#     l1.append(s2[len(s1):])
#     print("".join(l1))



l1 = []
for i in range(min(len(s1), len(s2))):
    l1.append(s1[i])
    l1.append(s2[i])
if len(s1) > len(s2):
    l1.append(s1[len(s2)+1: : ])
if len(s1) < len(s2):
    l1.append(s2[len(s1)+1 : ])

print("".join(l1))



cfg_old = "mode=debug;retry=3;timeout=30;log=on"
cfg_new = "mode=debug;retry=5;timeout=30"

# expected output
# {
#     "changed": {
#         "retry": ("3", "5")
#     },
#     "removed": ["log"]
# }







# diff = {}
# l1 = cfg_old.split(";")
# l2 = cfg_new.split(";")
#
# d_old = {}
# d_new = {}
# for i in l1:
#     key,value = i.split("=")
#     d_old[key] = value
#
# for i in l2:
#     key,value = i.split("=")
#     d_new[key] = value




# log = "User login successful: username=santosh, password=MySecret123"
# # output = User login successful: username=santosh, password=********
# ps = log.split(",")
# print(ps)


# x = 15
# y = 4
#
# z = (x // y) + (x % y)
#
# print(z)
#
# print(25 *2 == 50)
#

# text = "Python Programming"
#
# print(text.find("n"))
# print(text[text.find("n") + 1 : ].strip())

message = "Good Morning"
# print(message.lower().replace("morning", "evening"))
data = "apple,banana,cherry"

is_admin = True

is_logged_in = False

# print(is_admin and is_logged_in)
# my_list = [10, 20]
# my_list.append(30)
# print(my_list)
# my_list.insert(0,5)
# print(my_list)
# my_list[2] = 100
# # print(my_list)
# # my_list.up
#
# colors = ["red", "green", "blue", "green"]
# colors.remove("green")
# index = colors.index("green")
# # colors.pop(index)
# # print(colors)
#
#
# student = {"name": "Bob", "age": 22}



